config/routes.rb
Rails.application.routes.draw do
  resources :charts
	resources :reviews
  root 'studies#index'
  get 'pages/about'
  get 'pages/contact'

	devise_for :users do
  	get '/users/sign_out' => 'devise/sessions#destroy'
	end

  resources :studies do
    collection do
      get 'search'
    end
    resources :reviews, except: [:index]
  end

end

app/controllers/charts_controller.rb
class ChartsController < ApplicationController
  before_action :set_chart, only: [:show, :edit, :update, :destroy]

  # GET /charts
  # GET /charts.json
  def index
    gon.since_date=(Date.today - 2.years).to_s
    study_types=Study.completed_since(gon.since_date).collect{|s|s.study_type}.flatten
    study_phases=Study.completed_since(gon.since_date).collect{|s|s.phase}.flatten
    count_hash = Hash.new(0)
    study_types.each{|x|count_hash[x] += 1 if x}
    gon.type_counts=@type_count=count_hash.collect{|k,v| [k,v] if k }

    count_hash = Hash.new(0)
    study_phases.each{|x|count_hash[x] += 1 if x}
    gon.phase_counts=@phase_count=count_hash.collect{|k,v| [k,v] if k }
  end

  # GET /charts/1
  # GET /charts/1.json
  def show
  end

  # GET /charts/new
  def new
    @chart = Chart.new
  end

  # GET /charts/1/edit
  def edit
  end

  # POST /charts
  # POST /charts.json
  def create
    @chart = Chart.new(chart_params)

    respond_to do |format|
      if @chart.save
        format.html { redirect_to @chart, notice: 'Chart was successfully created.' }
        format.json { render :show, status: :created, location: @chart }
      else
        format.html { render :new }
        format.json { render json: @chart.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /charts/1
  # PATCH/PUT /charts/1.json
  def update
    respond_to do |format|
      if @chart.update(chart_params)
        format.html { redirect_to @chart, notice: 'Chart was successfully updated.' }
        format.json { render :show, status: :ok, location: @chart }
      else
        format.html { render :edit }
        format.json { render json: @chart.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /charts/1
  # DELETE /charts/1.json
  def destroy
    @chart.destroy
    respond_to do |format|
      format.html { redirect_to charts_url, notice: 'Chart was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_chart
      sponsors=Study.all[0..20].collect{|s|s.sponsors}.flatten
      agencies=sponsors.collect{|a| a.agency}
      count_hash = Hash.new(0)
      agencies.each{|agency|count_hash[agency] += 1 if agency}
      @sponsor_count=count_hash.collect{|k,v| [k,v] if k }
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def chart_params
      params[:chart]
    end
end

app/helpers/charts_helper.rb
module ChartsHelper
end

app/views/charts/_form.html.erb
<%= form_for(@chart) do |f| %>
  <% if @chart.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@chart.errors.count, "error") %> prohibited this chart from being saved:</h2>

      <ul>
      <% @chart.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/charts/edit.html.erb
<h1>Editing Chart</h1>

<%= render 'form' %>

<%= link_to 'Show', @chart %> |
<%= link_to 'Back', charts_path %>

app/views/charts/index.html.erb
<script type="text/javascript" src="https://www.google.com/jsapi"></script>
<script type="text/javascript">
      google.load('visualization', '1.0', {'packages':['corechart']});
      google.setOnLoadCallback(drawChart);
      google.setOnLoadCallback(drawPhasePieChart);
      google.setOnLoadCallback(drawPhaseBarChart);

      function drawChart() {
        var data = new google.visualization.DataTable();
        data.addColumn('string', 'Study Type');
        data.addColumn('number', 'Count');
        data.addRows(gon.type_counts);
        var options = {'title':'Study Distribution by Type - Studies Completed Since ' + gon.since_date,
          'width':700,
          'height':500};

         var chart = new google.visualization.PieChart(document.getElementById('type_chart_div'));
         chart.draw(data, options);
       }

      function drawPhasePieChart() {
        var data = new google.visualization.DataTable();
        data.addColumn('string', 'Phase');
        data.addColumn('number', 'Count');
        data.addRows(gon.phase_counts);
        var options = {'title':'Study Distribution by Phase - Studies Completed Since ' + gon.since_date,
          'width':700,
          'height':500};

         var chart = new google.visualization.PieChart(document.getElementById('phase_pie_chart_div'));
         chart.draw(data, options);
       }

      function drawPhaseBarChart() {
        var data = new google.visualization.DataTable();
        data.addColumn('string', 'Phase');
        data.addColumn('number', 'Count');
        data.addRows(gon.phase_counts);
        var options = {'title':'Study Distribution by Phase - Studies Completed Since ' + gon.since_date,
          'width':700,
          'height':500};

         var chart = new google.visualization.BarChart(document.getElementById('phase_bar_chart_div'));
         chart.draw(data, options);
       }
</script>

<body>
<div id="type_chart_div" data-count="<%= @type_count %>"></div>
<div id="phase_pie_chart_div" data-count="<%= @type_count %>"></div>
<div id="phase_bar_chart_div" data-count="<%= @phase_count %>"></div>
</body>

app/views/charts/new.html.erb
<h1>New Chart</h1>

<%= render 'form' %>

<%= link_to 'Back', charts_path %>

app/views/charts/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_chart_path(@chart) %> |
<%= link_to 'Back', charts_path %>