config/routes.rb
Rails.application.routes.draw do
  resources :charts
	resources :reviews
  root 'studies#index'
  get 'pages/about'
  get 'pages/contact'

	devise_for :users do
  	get '/users/sign_out' => 'devise/sessions#destroy'
	end

  resources :studies do
    collection do
      get 'search'
    end
    resources :reviews, except: [:index]
  end

end

app/models/study.rb
require 'csv'
	class Study < ActiveRecord::Base
		attr_accessor :xml
		establish_connection "ctgov_#{Rails.env}".to_sym if Rails.env != 'test'
		searchkick

		scope :interventional,  -> {where(study_type: 'Interventional')}
		scope :observational,   -> {where(study_type: 'Observational')}
		scope :current, -> { where("first_received_date >= '2007/10/01' and study_type='Interventional'") }

		def self.current_interventional
			self.interventional and self.current
		end

		self.primary_key = 'nct_id'
		has_many :reviews,				       :foreign_key => 'nct_id', dependent: :destroy

		has_one  :brief_summary,         :foreign_key => 'nct_id', dependent: :destroy
		has_one  :design,                :foreign_key => 'nct_id', dependent: :destroy
		has_one  :detailed_description,  :foreign_key => 'nct_id', dependent: :destroy
		has_one  :eligibility,           :foreign_key => 'nct_id', dependent: :destroy
		has_one  :participant_flow,      :foreign_key => 'nct_id', dependent: :destroy
		has_one  :result_detail,         :foreign_key => 'nct_id', dependent: :destroy

		has_many :expected_groups,       :foreign_key => 'nct_id', dependent: :destroy
		has_many :expected_outcomes,     :foreign_key => 'nct_id', dependent: :destroy
		has_many :groups,                :foreign_key => 'nct_id', dependent: :destroy
		has_many :outcomes,              :foreign_key => 'nct_id', dependent: :destroy
		has_many :baseline_measures,     :foreign_key => 'nct_id', dependent: :destroy
		has_many :browse_conditions,     :foreign_key => 'nct_id', dependent: :destroy
		has_many :browse_interventions,  :foreign_key => 'nct_id', dependent: :destroy
		has_many :conditions,            :foreign_key => 'nct_id', dependent: :destroy
		has_many :drop_withdrawals,      :foreign_key => 'nct_id', dependent: :destroy
		has_many :facilities,            :foreign_key => 'nct_id', dependent: :destroy
		has_many :interventions,         :foreign_key => 'nct_id', dependent: :destroy
		has_many :keywords,              :foreign_key => 'nct_id', dependent: :destroy
		has_many :links,                 :foreign_key => 'nct_id', dependent: :destroy
		has_many :milestones,            :foreign_key => 'nct_id', dependent: :destroy
		has_many :location_countries,    :foreign_key => 'nct_id', dependent: :destroy
		has_many :outcome_measures,      :foreign_key => 'nct_id', dependent: :destroy
		has_many :overall_officials,     :foreign_key => 'nct_id', dependent: :destroy
		has_many :oversight_authorities, :foreign_key => 'nct_id', dependent: :destroy
		has_many :reported_events,       :foreign_key => 'nct_id', dependent: :destroy
		has_many :responsible_parties,   :foreign_key => 'nct_id', dependent: :destroy
		has_many :result_agreements,     :foreign_key => 'nct_id', dependent: :destroy
		has_many :result_contacts,       :foreign_key => 'nct_id', dependent: :destroy
		has_many :secondary_ids,         :foreign_key => 'nct_id', dependent: :destroy
		has_many :sponsors,              :foreign_key => 'nct_id', dependent: :destroy
		has_many :references,            :foreign_key => 'nct_id', dependent: :destroy

		scope :started_between, lambda {|sdate, edate| where("start_date >= ? AND created_at <= ?", sdate, edate )}
		scope :changed_since,   lambda {|cdate| where("last_changed_date >= ?", cdate )}
		scope :completed_since, lambda {|cdate| where("completion_date >= ?", cdate )}
		scope :sponsored_by,    lambda {|agency| joins(:sponsors).where("sponsors.agency LIKE ?", "#{agency}%")}

		def initialize(hash)
			super
			@xml=hash[:xml]
			self.nct_id=hash[:nct_id]
		end

		def opts
			{
				:xml=>xml,
				:nct_id=>nct_id
			}
		end

		def self.all_nctids
		  all.collect{|s|s.nct_id}
		end

		def create
			update(attribs)
			self.sponsor_type              = calc_sponsor_type
			self.actual_duration           = calc_actual_duration
			self.derived_enrollment        = calc_enrollment
			self.results_reported          = calc_results_reported
			self.months_to_report_results  = calc_months_to_report_results
			self.registered_in_fiscal_year = calc_registered_in_fiscal_year
			self.number_of_facilities      = calc_number_of_facilities
			self.number_of_sae_subjects    = calc_number_of_sae_subjects
			self.number_of_nsae_subjects   = calc_number_of_nsae_subjects
			self.save!
			self
		end

		def description
			detailed_description.description
		end

		def summary
			brief_summary.description
		end

		def sampling_method
			eligibility.sampling_method
		end

		def study_population
			eligibility.study_population
		end

		def study_references
			references.select{|r|r.type!='results_reference'}
		end

		def result_references
			references.select{|r|r.type=='results_reference'}
		end

		def healthy_volunteers?
			eligibility.healthy_volunteers
		end

		def minimum_age
			eligibility.minimum_age
		end

		def maximum_age
			eligibility.maximum_age
		end

		def age_range
			"#{minimum_age} - #{maximum_age}"
		end

		def lead_sponsor
			sponsors.select{|s|s.sponsor_type=='lead'}.first
		end

		def collaborators
			sponsors.select{|s|s.sponsor_type=='collaborator'}
		end

		def lead_sponsor_name
			lead_sponsor.try(:agency)
		end

		def number_of_sites
			facilities.size
		end

		def pi
			val=''
			responsible_parties.each{|r|val=r.investigator_full_name if r.responsible_party_type=='Principal Investigator'}
			val
		end

		def calc_sponsor_type
			val=lead_sponsor.try(:agency_class)
			return val if val=='Industry' or val=='NIH'
			collaborators.each{|c|return 'NIH' if c.agency_class=='NIH'}
			collaborators.each{|c|return 'Industry' if c.agency_class=='Industry'}
			return 'Other'
		end

		def calc_number_of_sae_subjects
			cnt=0
			reported_events.each{|re|cnt=cnt+re.subjects_affected if re.event_type.downcase == 'serious'}
			cnt
		end

		def calc_number_of_nsae_subjects
			cnt=0
			reported_events.each{|re|cnt=cnt+re.subjects_affected if re.event_type.downcase != 'serious'}
			cnt
		end

		def calc_registered_in_fiscal_year
			if first_received_date.month < 10
				first_received_date.year
			else
				(first_received_date + 1.years).year
			end
		end

		def calc_number_of_facilities
			facilities.size
		end

		def calc_actual_duration
			return if !primary_completion_date or !start_date
			(primary_completion_date - start_date).to_f/365
		end

		def calc_results_reported
			results_reported=1 if outcomes.size > 0
		end

		def months_to_report_results
			return nil if first_received_results_date.nil? or primary_completion_date.nil?
			((first_received_results_date.to_time -  primary_completion_date.to_time)/1.month.second).to_i
		end

		def calc_enrollment
			cnt=0
			groups.each{|g|cnt=cnt+g.participant_count}
			cnt if cnt > 0
		end

		def status
			overall_status
		end

		def name
			brief_title
		end

		def recruitment_details
			result_detail.try(:recruitment_details)
		end

		def pre_assignment_details
			result_detail.try(:pre_assignment_details)
		end

		def attribs
			{
				:start_date => get_date(get('start_date')),
				:first_received_date => get_date(get('firstreceived_date')),
				:verification_date => get_date(get('verification_date')),
				:last_changed_date => get_date(get('lastchanged_date')),
				:primary_completion_date => get_date(get('primary_completion_date')),
				:completion_date => get_date(get('completion_date')),
				:first_received_results_date => get_date(get('firstreceived_results_date')),

				:start_date_str => get('start_date'),
				:first_received_date_str => get('firstreceived_date'),
				:verification_date_str => get('verification_date'),
				:last_changed_date_str => get('lastchanged_date'),
				:primary_completion_date_str => get('primary_completion_date'),
				:completion_date_str => get('completion_date'),
				:first_received_results_date_str => get('firstreceived_results_date'),
				:download_date_str => xml.xpath('//download_date'),

				:org_study_id => xml.xpath('//org_study_id').inner_html,
				:acronym =>get('acronym'),
				:number_of_arms => get('number_of_arms'),
				:number_of_groups =>get('number_of_groups'),
				:source => get('study_source'),
				:brief_title  => get('brief_title') ,
				:official_title => get('official_title'),
				:overall_status => get('overall_status'),
				:phase => get('phase'),
				:target_duration => get('target_duration'),
				:reported_enrollment => get('enrollment'),
				:biospec_description =>get_text('biospec_descr').strip,

				:primary_completion_date_type => get_type('primary_completion_date'),
				:completion_date_type => get_type('completion_date'),
				:enrollment_type => get_type('enrollment'),
				:study_type => get('study_type'),
				:biospec_retention =>get('biospec_retention').strip,
				:limitations_and_caveats  =>get('limitations_and_caveats'),

				:is_section_801 => get_boolean('is_section_801'),
				:is_fda_regulated => get_boolean('is_fda_regulated'),
				:has_expanded_access => get_boolean('has_expanded_access'),
				:has_dmc => get_boolean('has_dmc'),
				:why_stopped =>get('why_stopped').strip,
				#:delivery_mechanism =>delivery_mechanism,

				:expected_groups =>       ExpectedGroup.create_all_from(opts),
				:groups =>                Group.create_all_from(opts.merge(:study_xml=>xml)),
				:detailed_description =>  DetailedDescription.create_from(opts),
				:design =>                Design.create_from(opts),
				:brief_summary        =>  BriefSummary.create_from(opts),
				:eligibility =>           Eligibility.create_from(opts),
				:participant_flow     =>  ParticipantFlow.create_from(opts),
				:result_detail =>         ResultDetail.create_from(opts),
				:baseline_measures =>     BaselineMeasure.create_all_from(opts),
				:browse_conditions =>     BrowseCondition.create_all_from(opts),
				:browse_interventions =>  BrowseIntervention.create_all_from(opts),
				:conditions =>            Condition.create_all_from(opts),
				:facilities =>            Facility.create_all_from(opts),
				:interventions =>         Intervention.create_all_from(opts),

app/controllers/studies_controller.rb
class StudiesController < ApplicationController
  before_action :set_study, only: [:show, :edit]

  def search
    if params[:search].present?
      @studies = Study.all
      @studies = Study.search(params[:search])
    else
      @studies = Study.all
    end
  end

  # GET /studies
  # GET /studies.json
  def index
    #@studies=Study.sponsored_by('Duke')
    @studies=Study.all
    @definitions=DataDefinition.all
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_study
			id=params[:id]
      @study = Study.find_by_nct_id(id)
    end

end

app/helpers/studies_helper.rb
module StudiesHelper
end

app/views/studies/edit.html.erb
<script src="/assets/bootstrap-tooltip.js?body=1" type="text/javascript"></script>
<script src="/assets/bootstrap-popover.js?body=1" type="text/javascript"></script>

<script type="text/javascript">
$(document).ready(function(){
  $('.has-tooltip').tooltip();
  $('.has-popover').popover({
    trigger: 'hover'
  });

  $('.sponsor-popover').popover({ html : true });
});
</script>

<p id="notice"><%= notice %></p>

<div class="container-fluid">
<section id='form form-horizontal well'>
<%= form_for(@study) do |s| %>
  <h2>
    <%= @study.nct_id %>
    <span>
      <%= @study.brief_title %>
      <% if !@study.acronym.blank? %>
        (<%= @study.acronym %>)
      <% end %>
    </span>
  </h2>

  <div class='well'>
    <button type="button"
	    class="btn btn-link has-popover"
	    data-toggle="popover"
            data-content="<%= DataDefinition.nlm_info_for('sponsor_type') %>">Lead Sponsor: </button>
    <%= @study.lead_sponsor.agency %>
    <% if !@study.org_study_id.blank? %>
      <button type="button"
	    class="btn btn-link has-popover"
	    data-toggle="popover"
            data-content="<%= DataDefinition.nlm_info_for('org_study_id') %>">
	    (<%= @study.org_study_id %>)</button>
     <% end %>
    <div>
      <button type="button"
	    class="btn btn-link has-popover"
	    data-toggle="popover"
            data-content="<%= DataDefinition.nlm_info_for('study_design') %>">
	    <%= @study.study_type %></button>

      <button type="button"
	    class="btn btn-link has-popover"
	    data-toggle="popover"
            data-content="<%= DataDefinition.nlm_info_for('phase') %>">
            <%= @study.phase %></button>

      <button type="button"
	    class="btn btn-link has-popover"
	    data-toggle="popover"
            data-content="<%= DataDefinition.nlm_info_for('overall_status') %>">
            <%= @study.overall_status %></button>

    </div>
    <% if !@study.start_date.blank? %>
      <div>
      <button type="button"
	    class="btn btn-link has-popover"
	    data-toggle="popover"
            data-content="<%= DataDefinition.nlm_info_for('start_date') %>">
	    Started: </button>
      </button>
        <%= @study.start_date %>
      </div>
    <% end %>
    <% if !@study.first_received_date.blank? %>
      <div>
        <button type="button"
	    class="btn btn-link has-popover"
	    data-toggle="popover"
            data-content="<%= DataDefinition.ctti_info_for('firstreceived_date') %>">
	    First Received: </button>
        <%= @study.first_received_date %>
      </div>
    <% end %>
    <% if !@study.completion_date.blank? %>
      <div>
        Completed: <%= @study.completion_date %>
      </div>
    <% end %>
  </div>

  <div class='well'>
    <div>
      <%= @study.brief_summary.description %>
    </div>
  </div>

  <% if @study.keywords.size > 0 %>
    <h2>Keywords</h2>
    <div class='well'>
      <% @study.keywords.each do |k| %>
          <p class='keyword'><%= k.name %></td>
      <% end %>
    </div>
  <% end %>

  <% if @study.facilities.size > 0 %>
    <h2>Facilities</h2>
    <div class='table-responsive well'>
      <table id="facilitiesTable" class='table table-striped table-condensed table-hover' width='100%'>
      <thead>
      <tr>
	<th>name</th>
	<th>city</th>
	<th>state</th>
      </tr>
      <thead>
      <% @study.facilities.each do |fac| %>
	<tr>
          <td class="facility_element"><%= fac.name %></td>
          <td class="facility_element"><%= fac.city %></td>
          <td class="facility_element"><%= fac.state %></td>
	</tr>
      <% end %>
      </table>
    </div>
  <% end %>

  <% if @study.expected_outcomes.size > 0 %>
    <h2>Prespecified Outcomes</h2>
    <div class='table-responsive well'>
      <table id="expectedOutcomesTable" class='table table-striped table-condensed table-hover' width='100%'>
      <thead>
      <tr>
	<th>type</th>
	<th>measure</th>
	<th>time frame</th>
      </tr>
      </thead>
      <% @study.expected_outcomes.each do |o| %>
        <tr>
          <td class="out"><%= o.outcome_type %></td>
          <td class="out"><%= o.measure %></td>
          <td class="out"><%= o.time_frame %></td>
         </tr>
      <% end %>
      </table>
    </div>
   <% end %>

  <% if @study.reported_events.size > 0 %>
    <h2>Reported Events</h2>
      <div class='table-responsive well'>
      <table id="eventsTable" class='table table-striped table-condensed table-hover' width='100%'>
      <thead>
      <tr>
	<th class='span3'>type</th>
	<th>id</th>
	<th>group desc</th>
	<th>assessment</th>
	<th># at risk</th>
	<th># affected</th>
	<th>events</th>
      </tr>
      </thead>
      <% @study.reported_events.sort_by{|re|re.ctgov_group_enumerator}.each do |o| %>
				  <% if o.subjects_affected != 0 and o.event_count != 0 %>
          	<tr>
            	<td><%= o.type %></td>
            	<td><%= o.ctgov_group_id %></td>
            	<td><%= o.group_title %></td>
            	<td><%= o.title %></td>
            	<td><%= o.subjects_at_risk %></td>
            	<td><%= o.subjects_affected %></td>
            	<td><%= o.event_count %></td>
          	</tr>
   				<% end %>
      <% end %>
      </table>
    </div>
   <% end %>

  </div>
<% end %>

</section>
</div>
<%= link_to 'Back', studies_path %>

app/views/studies/index.html.erb
<div class="container-fluid">
<script>
$(document).ready(function(){
    $('#sortTable').dataTable();
});
</script>

<div class='table-responsive'>
<table id="sortTable" class='table table-striped table-condensed table-hover' width='100%'>
  <thead>
    <tr>
      <th>status</th>
      <th>conditions</th>
      <th>interventions</th>
      <th>title</th>
      <th>started</th>
      <th>lead sponsor</th>
			<th>actions</th>
	</tr>
  </thead>
  <colgroup>
    <col class="col-md-1">
    <col class="col-md-4">
    <col class="col-md-4">
    <col class="col-md-6">
    <col class="col-md-4">
    <col class="col-md-4">
    <col class="col-md-1">
  </colgroup>

  <tbody>
    <% @studies.each do |study| %>
      <tr>
        <td><%= study.overall_status %></td>
        <td><%= study.condition_names %></td>
        <td><%= study.intervention_names %></td>
        <td><%= study.brief_title %></td>
        <td><%= study.start_date %></td>
        <td><%= study.lead_sponsor.try(:agency) %></td>
				<td class='duke-btn'>
					<%= link_to 'View Details',edit_study_path(study), :class => "btn btn-default btn-mini" %>
					<%= link_to 'Contribute',study_path(study), :class => "btn btn-default btn-mini" %>
			  </td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
</div>

app/views/studies/search.html.erb
<div class="container-fluid">
<script>
$(document).ready(function(){
    $('#sortTable').dataTable();
});
</script>

<div class='table-responsive'>
<table id="sortTable" class='table table-striped table-condensed table-hover' width='100%'>
  <thead>
    <tr>
      <th>status</th>
      <th>conditions</th>
      <th>interventions</th>
      <th>title</th>
      <th>started</th>
      <th>lead sponsor</th>
			<th>actions</th>
	</tr>
  </thead>
  <colgroup>
    <col class="col-md-1">
    <col class="col-md-4">
    <col class="col-md-4">
    <col class="col-md-6">
    <col class="col-md-4">
    <col class="col-md-4">
    <col class="col-md-1">
  </colgroup>

  <tbody>
    <% @studies.each do |study| %>
      <tr>
        <td><%= study.overall_status %></td>
        <td><%= study.condition_names %></td>
        <td><%= study.intervention_names %></td>
        <td><%= study.brief_title %></td>
        <td><%= study.start_date %></td>
        <td><%= study.lead_sponsor.try(:agency) %></td>
				<td class='duke-btn'>
					<%= link_to 'View Details',edit_study_path(study), :class => "btn btn-default btn-mini" %>
					<%= link_to 'Contribute',study_path(study), :class => "btn btn-default btn-mini" %>
			  </td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
</div>

app/views/studies/show.html.erb
<div class="row">
  <div class="col-md-3">

    <h4>
      <%= @study.acronym %>
      <%= @study.brief_title %>
    </h4>

    <div class="star-rating" data-score= <%= @study.average_rating %> ></div>
    <p><%= "#{@study.reviews.length} reviews" %></p>

    <p>
			<li><i class="fa-li fa fa-check-square"></i> <%= @study.overall_status %></li>
			<li><i class="fa-li fa fa-check-square"></i> <%= @study.study_type %></li>
			<li><i class="fa-li fa fa-check-square"></i> <%= @study.phase %></li>
    </p>

    <p>
      <%= @study.prime_address %>
    </p>

    <p>

		<%= link_to "Write a Review", new_review_path(:nct_id=>@study.nct_id), class: "btn btn-primary" %>

		<%= link_to 'Return to List', studies_path, class: "btn btn-primary" %>

    <br>
    <br>

    <iframe
      width="230"
      height="230"
      frameborder="0" style="border:0"
      src="https://www.google.com/maps/embed/v1/place?key=AIzaSyBJg0HiO2KtvExTuiWB6rKhmUUsHXFk6dY
        &q=<%= @study.prime_address.parameterize %>&zoom=14">
    </iframe>
  </div>

  <div class="col-md-9">
    <% if @study.reviews.blank? %>
      <h3>No reviews yet. Be the first to write one!</h3>
    <% else %>
      <table class="table">
        <thead>
          <tr>
            <th class="col-md-3"></th>
            <th class="col-md-9"></th>
          </tr>
        </thead>

        <tbody>
          <% @study.reviews.each do |review| %>
            <tr>
              <td>
                <h4>
                  <%= "#{review.user.first_name.capitalize} #{review.user.last_name.capitalize[0]}." %>
                </h4>
                <p><%= review.created_at.strftime("%-m/%-d/%y") %></p>
              </td>

              <td>
                <div class="star-rating" data-score= <%=review.rating %> ></div>
                <p><%= h(review.comment).gsub(/\n/, '<br/>').html_safe %></p>
                <% if user_signed_in? %>
									<td><%= link_to 'Edit', edit_review_path(review), data: {:id=>review.id}, class: "btn btn-link" %></td>
									<td><%= link_to 'Destroy', review, method: :delete, data: {confirm: 'Are you sure?',:id=>review.id}, class: "btn btn-link" %></td>
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    <% end %>
  </div>
</div>

<%= link_to 'Edit', edit_study_path(@study), class: "btn btn-link" %> |
<%= link_to 'Back', studies_path, class: "btn btn-link" %>

<script>
  $('.star-rating').raty({
    path: 'https://s3.amazonaws.com/yelpdemo/stars',
    readOnly: true,
    score: function() {
      return $(this).attr('data-score');
    }
  });
</script>